# Generated by Django 3.1.7 on 2021-04-21 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elsysapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='data',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='xData',
            field=models.CharField(default=django.utils.timezone.now, max_length=15000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='yData',
            field=models.CharField(default=1, max_length=15000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='zData',
            field=models.CharField(default=1, max_length=15000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
